services:
# C Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.nvidia

    container_name: mandelbrot_backend
    restart: unless-stopped
    environment:
      - MANDELBROT_THREADS=0
      - MANDELBROT_NVIDIA_GPU=1     # Set to 1 to enable GPU acceleration
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    expose:
      - "8080" # Only exposed to internal Docker network, not the host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Nginx Frontend Service
  frontend:
    build: ./frontend
    container_name: mandelbrot_frontend
    restart: unless-stopped
    ports:
      - "8080:80" # Map host port 80 to container port 80
    depends_on:
      - backend
